# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 86cf7f2a3a0a0c1f31016de7e7c57e713b5f05dbf77ae21e2d6c6bde9da6408f8c0d7b49884ba4fc5ef89c6ea863568bfb2563c83ae9d3b6deda8b13a759ff02

test:
  secret_key_base: 34b6f698ab11930b5f6cdf3aa386d8d7a4d199d47155a48ed61b684e86c71f52960c219afcc051d44eea6b41f201a51fc11bc90943e6160e0030c0efe683b08b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
